#include <stdio.h>
#include <stdlib.h>

/**
 * main - finds and prints the sum of the even-valued terms and add a new line
 * Each new term in the Fibonacci sequence is generated by adding the previous
 * two terms, by starting with 1 and 2, the first 10
 * terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89
 * Fibonacci sequence whose values do not exceed 4,000,000
 * Return: Always 0
 */
int main(void)
{
	int s = 0, t = 1, next = 0;
	int n = 0;

	while (next < 4000000)
	{
		next = s + t;
		s = t;
		t = next;
		if (next % 2 == 0)
			n += next;
	}
	printf("%i\n", n);
	return (0);
}
